# ------------------------------------------------------------
# default_server
# ------------------------------------------------------------

server {
  listen 80 default_server;
  listen [::]:80 default_server;

  server_name default-host.localhost;
  access_log /var/log/angie/default-host.access.log combined;
  error_log /var/log/angie/default-host.error.log warn;

  root /usr/share/angie/html/default_www;

  location / {
    try_files $uri /index.html;
  }
}
