---
- name: "USB-Vault/unlock: Opens the LUKS container using a vault-encrypted passphrase."
  ansible.builtin.include_tasks:
    file: unlock.yml
    apply:
      tags: [usb_unlock]
  tags: [usb_unlock]

- name: "USB-Vault/lock: Closes the LUKS container and wipes the mapping."
  ansible.builtin.include_tasks:
    file: lock.yml
    apply:
      tags: [usb_lock]
  tags: [usb_lock]

- name: "USB-Vault/unmount: Safely unmounts the filesystem."
  ansible.builtin.include_tasks:
    file: unmount.yml
    apply:
      tags: [usb_unmount]
  tags: [usb_unmount]

- name: "USB-Vault/all: Performs both unlock and mount"
  ansible.builtin.include_tasks:
    file: all.yml
    apply:
      tags: [usb_all]
  tags: [usb_all]

- name: "USB-Vault/new: Configure a new USB Vault"
  ansible.builtin.include_tasks:
    file: new.yml
    apply:
      tags: [usb_new]
  tags: [usb_new]
