---
- name: "USB-Vault/new: Load USB passphrase"
  ansible.builtin.include_tasks: passphrase.yml

- name: "USB-Vault/new: Load USB device path"
  ansible.builtin.include_tasks: device.yml

- name: "USB-Vault/new: Ask for USB device path (confirmation)"
  ansible.builtin.pause:
    prompt: |
      [WARNING]: You are about to perform a DESTRUCTIVE operation on the device.
      This action will ERASE all information and re-create partition table.

      Press ENTER the device path again to continue or CTRL+C then 'A' to abort.
  register: usb_device_2

- name: "USB-Vault/new: Confirming the device creation"
  ansible.builtin.assert:
    that:
      - usb_device == usb_device_2.user_input
    fail_msg: "Paths do not match, aborting the operation."

- name: "USB-Vault/new: Setup a LUKS container"
  become: true
  block:
    - name: "USB-Vault/new: Remove existing LUKS container"
      community.crypto.luks_device:
        device: "{{ usb_device }}"
        state: absent
      when: force_recreate_usb_luks | default(false) | bool

    - name: "USB-Vault/new: Create and Open LUKS container with a passphrase"
      community.crypto.luks_device:
        device: "{{ usb_device }}"
        state: opened
        name: usb-vault
        passphrase: "{{ usb_passphrase }}"
      register: usb_luks_device

    - name: "USB-Vault/new: Create a ext4 filesystem on opened LUKS container"
      community.general.filesystem:
        fstype: ext4
        dev: /dev/mapper/usb-vault

    - name: "USB-Vault/new: Create a mount point"
      ansible.builtin.file:
        path: "{{ usb_mount_dir }}"
        state: directory
        mode: "0755"
      register: usb_mount

    - name: "USB-Vault/new: Mount up the LUKS container"
      ansible.posix.mount:
        path: "{{ usb_mount_dir }}"
        src: /dev/mapper/usb-vault
        fstype: ext4
        state: ephemeral

- name: "USB-Vault/new: Identify UUID of the USB disk"
  ansible.builtin.command: "blkid -s UUID -o value {{ usb_device }}"
  register: blkid_cmd
  changed_when: false

- name: "USB-Vault/new: Save UUID for future use"
  when: usb_uuid is not defined or usb_uuid != blkid_cmd.stdout
  block:
    - name: "USB-Vault/new: Ensure host_vars directory exists"
      ansible.builtin.file:
        path: "{{ playbook_dir }}/group_vars/all"
        state: directory
        mode: "0755"
      delegate_to: localhost

    - name: "USB-Vault/new: Set the UUID fact(s)"
      ansible.builtin.set_fact:
        old_usb_uuid: "{{ usb_uuid | default(omit) }}"
        usb_uuid: "{{ blkid_cmd.stdout }}"

    - name: "USB-Vault/new: Persist UUID to host_vars"
      ansible.builtin.copy:
        dest: "{{ playbook_dir }}/group_vars/all/usb.yml"
        content: |
          ---
          usb_uuid: {{ blkid_cmd.stdout }}
          {% if usb_uuid is defined %}
          old_usb_uuid: {{ usb_uuid }}
          {% endif %}
        mode: "0644"
      delegate_to: localhost
