---
- name: "USB-Vault/passphrase: Define passphrase"
  when: usb_passphrase is not defined
  block:
    - name: "USB-Vault/passphrase: Ask for passphrase"
      ansible.builtin.pause:
        prompt: "Enter USB Passphrase"
        echo: false
      register: pass_one

    - name: "USB-Vault/passphrase: Ask for passphrase (confirmation)"
      ansible.builtin.pause:
        prompt: "Confirm USB Passphrase"
        echo: false
      register: pass_two

    - name: "USB-Vault/passphrase: Verify passphrases match"
      ansible.builtin.assert:
        that:
          - pass_one.user_input == pass_two.user_input
        fail_msg: "Passphrases do not match! Please run the playbook again."

    - name: "USB-Vault/passphrase: Set the passphrase fact"
      ansible.builtin.set_fact:
        usb_passphrase: "{{ pass_one.user_input }}"
