---
- block:
    - name: "Ask for passphrase"
      ansible.builtin.pause:
        prompt: "Enter USB Passphrase"
        echo: false
      register: pass_one

    - name: "Ask for passphrase (confirmation)"
      ansible.builtin.pause:
        prompt: "Confirm USB Passphrase"
        echo: false
      register: pass_two

    - name: "Verify passphrases match"
      ansible.builtin.assert:
        that:
          - pass_one.user_input == pass_two.user_input
        fail_msg: "Passphrases do not match! Please run the playbook again."

    - name: "Set the passphrase fact"
      set_fact:
        usb_passphrase: "{{ pass_one.user_input }}"
  when: usb_passphrase is not defined
