---
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
  namespace: {{ cilium_namespace }}
spec:
  bgpInstances:
  - name: instance-65101
    localASN: 65101
    localPort: 179
    peers:
    - name: peer-65551-opnsense
      peerASN: {{ bgp_opnsense_asn }}
      autoDiscovery:
        mode: DefaultGateway
        defaultGateway:
          addressFamily: ipv4
      peerConfigRef:
        name: opnsense-peer
