---
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: opnsense-peer
spec:
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  # authSecretRef: bgp-opnsense-secret
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: bgp
