---
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
spec:
  advertisements:
    - advertisementType: Service
      service:
        addresses:
          - ExternalIP
          - LoadBalancerIP
      selector:
        matchLabels:
          service.kubernetes.io/advertise-bgp: "true"
