---
- name: "Telemetry/alloy: Create volume directories"
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    state: directory
    owner: "{{ _quadlet.owner }}"
    group: "{{ _quadlet.group }}"
    mode: "0755"
  loop: "{{ _quadlet.mount_src }}"

- name: "Telemetry/alloy: Generate quadlets"
  containers.podman.podman_container:
    name: "{{ _quadlet.name }}"
    state: quadlet
    quadlet_dir: "{{ _quadlet.quadlet_dir }}"
    volume:
      - "{{ _quadlet.mount_src[0] }}:/etc/alloy/config.alloy:Z,ro"
      - "/:/host:ro,rslave"
    image: "{{ _quadlet.image }}"
    dns: "{{ _quadlet.dns }}"
    network: "{{ _quadlet.network }}"
    ip: "{{ _quadlet.ip }}"
    mac_address: "{{ _quadlet.mac_address }}"
    cpus: "{{ _quadlet.cpus }}"
    memory: "{{ _quadlet.memory }}"
    quadlet_options:
      - "AutoUpdate=registry"
      - |

        {{ _quadlet.__systemd_service }}
        {{ _quadlet.__systemd_unit }}
        {{ _quadlet.__systemd_install.rstrip() }}
  vars:
    systemd_service:
      Restart: always
    systemd_unit:
      After:
        - telemetry.target
    systemd_install:
      WantedBy:
        - telemetry.target
  notify: "SystemD daemon reload"

- name: "Telemetry/alloy: Render etc"
  ansible.builtin.template:
    src: config.alloy.j2
    dest: "{{ _quadlet.mount_src[0] }}"
    mode: '0644'
  vars:
    config: "{{ services[ansible_role_name].config }}"
