---
- name: "Telemetry/alloy: Create volume directories"
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    state: directory
    owner: "{{ _quadlet.owner }}"
    group: "{{ _quadlet.group }}"
    mode: "0755"
  loop: "{{ _quadlet.mount_src }}"

# - name: "Telemetry/alloy: Copy custom SELinux CIL module"
#   ansible.builtin.copy:
#     src: selinux/alloy.cil
#     dest: "{{ selinux_local_module_path }}"
#     mode: '0644'
#   when: ansible_facts.selinux.status == "enabled"
#   register: cil_file
#
# - name: "Telemetry/alloy: Install SELinux CIL module"
#   ansible.builtin.shell: semodule -i selinux/alloy.cil /usr/share/udica/templates/{base_container.cil,log_container.cil}
#   changed_when: "{{ cil_file.changed }}"
#   when:
#     - ansible_facts.selinux.status == "enabled"
#     - cil_file.changed

- name: "Telemetry/alloy: Generate quadlets"
  containers.podman.podman_container:
    name: "{{ _quadlet.name }}"
    state: quadlet
    quadlet_dir: "{{ _quadlet.quadlet_dir }}"
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    env:
      ALLOY_DEPLOY_MODE: docker
    volume:
      - "{{ _quadlet.mount_src[0] }}:/etc/alloy/config.alloy:Z"
      - /var/log:/host/log:ro
    image: "{{ _quadlet.image }}"
    dns: "{{ _quadlet.dns }}"
    network: "{{ _quadlet.network }}"
    ip: "{{ _quadlet.ip }}"
    security_opt: "{{ ['label=type:alloy.process'] if (ansible_facts.selinux.status | default('disabled') == 'enabled') else omit }}"
    mac_address: "{{ _quadlet.mac_address }}"
    cpus: "{{ _quadlet.cpus }}"
    memory: "{{ _quadlet.memory }}"
    quadlet_options:
      - "AutoUpdate=registry"
      - |

        {{ _quadlet.__systemd_service }}
        {{ _quadlet.__systemd_unit }}
        {{ _quadlet.__systemd_install.rstrip() }}
  vars:
    systemd_service:
      Restart: always
    systemd_unit:
      After:
        - telemetry.target
    systemd_install:
      WantedBy:
        - telemetry.target
  register: quadlet_gen
  notify: "SystemD daemon reload"

- name: "Telemetry/alloy: Render etc"
  ansible.builtin.template:
    src: config.alloy.j2
    dest: "{{ _quadlet.mount_src[0] }}"
    mode: '0644'
  vars:
    config: "{{ services[ansible_role_name].config }}"

- name: "Telemetry/alloy: Validate config"
  containers.podman.podman_container_exec:
    name: "{{ _quadlet.name }}"
    command: alloy validate /etc/alloy/config.alloy

- name: "Telemetry/alloy: Run notified handlers now"
  ansible.builtin.meta: flush_handlers

- name: "Telemetry/alloy: Check if service is running"
  ansible.builtin.systemd:
    name: "{{ _quadlet.name }}.service"
  register: service_status
  when: >
    [
      quadlet_gen,
      render_alloy
    ] | selectattr('changed', 'defined') | selectattr('changed') | list | length > 0

- name: "Telemetry/alloy: Restart if service was running"
  ansible.builtin.service:
    name: "{{ _quadlet.name }}.service"
    state: restarted
  register: service_restart
  when: >
    (
      [
        quadlet_gen
      ] | selectattr('changed', 'defined') | selectattr('changed') | list | length > 0
    ) and service_status.status is defined
      and service_status.status.ActiveState == "active"

- name: "Telemetry/alloy: Reload if service was running"
  containers.podman.podman_container_exec:
    name: "{{ _quadlet.name }}"
    command: angie -s reload
  when: >
    (
      [
        render_alloy
      ] | selectattr('changed', 'defined') | selectattr('changed') | list | length > 0
    ) and service_status.status is defined
      and service_status.status.ActiveState == "active"
      and not service_restart.changed
