---
- name: "Telemetry/grafana: Create volume directories"
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    state: directory
    owner: 472  # Grafana user
    group: 0    # Grafana group
    mode: "0755"
  loop: "{{ _quadlet.mount_src }}"

- name: "Telemetry/grafana: Generate quadlets"
  containers.podman.podman_container:
    name: "{{ _quadlet.name }}"
    state: quadlet
    quadlet_dir: "{{ _quadlet.quadlet_dir }}"
    env:
      GF_SERVER_ROOT_URL: "{{ _services.config.grafana_server_root_url }}"
    volume:
      - "{{ _quadlet.mount_src[0] }}:/var/lib/grafana:Z"
      - "{{ _quadlet.mount_src[1] }}:/etc/grafana/provisioning/datasources/datasources.yaml:Z,ro"
    image: "{{ _quadlet.image }}"
    dns: "{{ _quadlet.dns }}"
    network: "{{ _quadlet.network }}"
    ip: "{{ _quadlet.ip }}"
    mac_address: "{{ _quadlet.mac_address }}"
    cpus: "{{ _quadlet.cpus }}"
    memory: "{{ _quadlet.memory }}"
    quadlet_options:
      - "AutoUpdate=registry"
      - |

        {{ _quadlet.__systemd_service }}
        {{ _quadlet.__systemd_unit }}
        {{ _quadlet.__systemd_install.rstrip() }}
  vars:
    systemd_service:
      Restart: always
    systemd_unit:
      After:
        - telemetry.target
    systemd_install:
      WantedBy:
        - telemetry.target
  notify: "SystemD daemon reload"

- name: "Telemetry/grafana: Render etc"
  ansible.builtin.template:
    src: grafana-datasources.yaml.j2
    dest: "{{ _quadlet.mount_src[1] }}"
    owner: 472  # Grafana user
    group: 0    # Grafana group
    mode: '0644'
  vars:
    config: "{{ services[ansible_role_name].config }}"
