---
- name: "Telemetry/systemd: telemetry target"
  ansible.builtin.copy:
    src: systemd/telemetry.target
    dest: /etc/systemd/system
    mode: "0644"
  notify: "SystemD daemon reload"

- name: "Telemetry/loki"
  ansible.builtin.include_tasks:
    file: loki.yml
    apply:
      tags: [telemetry_loki]
  vars:
    quadlet_container_name: loki
    quadlet_mount_src:
      - "{{ _quadlet.data ~ '/loki-config.yml' }}"
    quadlet_cpus: 2
    quadlet_memory: 512M
  tags: [telemetry_loki]

- name: "Telemetry/grafana"
  ansible.builtin.include_tasks:
    file: grafana.yml
    apply:
      tags: [telemetry_grafana]
  vars:
    quadlet_container_name: grafana
    quadlet_mount_src:
      - "{{ _quadlet.data ~ '/data/' }}"
      - "{{ _quadlet.data ~ '/grafana-datasources.yaml' }}"
    quadlet_cpus: 2
    quadlet_memory: 2G
  tags: [telemetry_grafana]

- name: "Telemetry/alloy"
  ansible.builtin.include_tasks:
    file: alloy.yml
    apply:
      tags: [telemetry_alloy]
  vars:
    quadlet_container_name: alloy
    quadlet_mount_src:
      - "{{ _quadlet.data ~ '/config.alloy' }}"
    quadlet_cpus: 2
    quadlet_memory: 512M
  tags: [telemetry_alloy]

- name: "Telemetry/tempo"
  ansible.builtin.include_tasks:
    file: tempo.yml
    apply:
      tags: [telemetry_tempo]
  vars:
    quadlet_container_name: tempo
    quadlet_mount_src:
      - "{{ _quadlet.data ~ '/tempo.yaml' }}"
      - "{{ _quadlet.data ~ '/data/' }}"
    quadlet_cpus: 2
    quadlet_memory: 512M
  tags: [telemetry_tempo]

- name: "Telemetry/prometheus"
  ansible.builtin.include_tasks:
    file: prometheus.yml
    apply:
      tags: [telemetry_prometheus]
  vars:
    quadlet_container_name: prometheus
    quadlet_mount_src:
      - "{{ _quadlet.data ~ '/prometheus.yaml' }}"
    quadlet_cpus: 2
    quadlet_memory: 1G
  tags: [telemetry_prometheus]

# - name: "Telemetry/prometheus-node-exporter"
#   ansible.builtin.include_tasks:
#     file: prometheus-node-exporter.yml
#     apply:
#       tags: [telemetry_prometheus-node-exporter]
#   vars:
#     quadlet_container_name: prometheus-node-exporter
#     quadlet_cpus: 1
#     quadlet_memory: 128M
#   tags: [telemetry_node-exporter]

- name: "Telemetry/prometheus-podman-exporter"
  ansible.builtin.include_tasks:
    file: podman-exporter.yml
    apply:
      tags: [telemetry_podman-exporter]
  vars:
    quadlet_container_name: prometheus-podman-exporter
    quadlet_cpus: 1
    quadlet_memory: 128M
  tags: [telemetry_podman-exporter]

- name: "Telemetry/graphite-exporter"
  ansible.builtin.include_tasks:
    file: graphite-exporter.yml
    apply:
      tags: [telemetry_graphite-exporter]
  vars:
    quadlet_container_name: graphite-exporter
    quadlet_mount_src:
      - "{{ _quadlet.data ~ '/truenas-mappings.yml' }}"
    quadlet_cpus: 1
    quadlet_memory: 128M
  tags: [telemetry_graphite-exporter]

- name: "Telemetry/apcupsd"
  ansible.builtin.include_tasks:
    file: apcupsd.yml
    apply:
      tags: [telemetry_apcupsd]
  vars:
    quadlet_container_name: apcupsd
    quadlet_mount_src:
      - "{{ _quadlet.data ~ '/apcupsd.conf' }}"
    quadlet_cpus: 1
    quadlet_memory: 128M
  tags: [telemetry_apcupsd]

- name: "Telemetry/apcupsd-exporter"
  ansible.builtin.include_tasks:
    file: apcupsd-exporter.yml
    apply:
      tags: [telemetry_apcupsd-exporter]
  vars:
    quadlet_container_name: apcupsd-exporter
    quadlet_cpus: 1
    quadlet_memory: 128M
  tags: [telemetry_apcupsd-exporter]

- name: "Telemetry/uptime-kuma"
  ansible.builtin.include_tasks:
    file: uptime-kuma.yml
    apply:
      tags: [telemetry_uptime-kume]
  vars:
    quadlet_container_name: uptime-kuma
    quadlet_mount_src:
      - "{{ _quadlet.data ~ '/data/' }}"
    quadlet_cpus: 1
    quadlet_memory: 512M
  tags: [telemetry_uptime-kuma]
