---
- name: "Telemetry/prometheus-podman-exporter: Generate quadlets"
  containers.podman.podman_container:
    name: "{{ _quadlet.name }}"
    state: quadlet
    quadlet_dir: "{{ _quadlet.quadlet_dir }}"
    env:
      CONTAINER_HOST: unix:///run/podman/podman.sock
    security_opt:
      - label=disable
    user: root
    volume:
      - "/run/podman/podman.sock:/run/podman/podman.sock"
    image: "{{ _quadlet.image }}"
    network: host
    cpus: "{{ _quadlet.cpus }}"
    memory: "{{ _quadlet.memory }}"
    quadlet_options:
      - "AutoUpdate=registry"
      - |

        {{ _quadlet.__systemd_service }}
        {{ _quadlet.__systemd_unit }}
        {{ _quadlet.__systemd_install.rstrip() }}
  vars:
    systemd_service:
      Restart: always
    systemd_unit:
      After:
        - telemetry.target
    systemd_install:
      WantedBy:
        - telemetry.target
  notify: "SystemD daemon reload"
