---
- name: "SystemD daemon reload"
  ansible.builtin.systemd_service:
    daemon_reload: true
  notify: "SystemD enable forge target"

- name: "SystemD enable and start forge target"
  ansible.builtin.service:
    state: started
    enabled: true
    name: forge.target
  listen: "SystemD daemon reload"
