# ------------------------------------------------------------
# cloud.alakx.com
# ------------------------------------------------------------

map $scheme $hsts_header {
  https "max-age=63072000; preload";
}

server {
  set $forward_scheme http;
  set $server         "10.0.50.24";
  set $port           80;

  listen 443 ssl;
  listen [::]:443 ssl;
  acme letsenc;

  server_name cloud.alakx.com;
  access_log /var/log/angie/cloud.alakx.com.access.log proxy;
  error_log /var/log/angie/cloud.alakx.com.error.log warn;
  proxy_buffering off;

  location /s/ {
    include conf/http.d/include/proxy.conf;
  }

  location /public.php/dav/files {
    include conf/http.d/include/proxy.conf;
  }

  location /core {
    include conf/http.d/include/proxy.conf;
  }

  location /apps {
    include conf/http.d/include/proxy.conf;
  }

  location /dist {
    include conf/http.d/include/proxy.conf;
  }

  status_zone $host zone=host_zone:10;
}
