# WordPress single site rules.
location / {
    # This is cool because no php is touched for static content.
    # include the "?$args" part so non-default permalinks doesn't break when using query string
    try_files $uri $uri/ /index.php?$args;
}

location ~ \.php$ {
    include conf/http.d/include/fastcgi.conf;
    fastcgi_intercept_errors on;
    fastcgi_pass $server:$port;
}

location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
    expires max;
    log_not_found off;
}
