- name: Wait for Cilium to be ready
  ansible.builtin.command: cilium status --wait --wait-duration 120s
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: cilium_status
  retries: 5
  delay: 10
  until: cilium_status.rc == 0
  changed_when: false
  when: cilium_install.changed

