options {
  directory       "/usr/local/etc/namedb/working";
  pid-file        "/var/run/named/pid";
  dump-file       "/var/dump/named_dump.db";
  statistics-file "/var/stats/named.stats";

  listen-on port 53    { any; };
  listen-on-v6 port 53 { any; };

  forwarders      { 9.9.9.9; 149.112.112.112; };
  response-policy { zone "whitelist.localdomain"; zone "blacklist.localdomain"; zone "rpz"; };

  max-cache-size    80%;
  dnssec-validation no;
};

key "rndc-key" {
  algorithm "hmac-sha256";
  secret "{{ rdnc_key }}";
};

controls {
  inet 127.0.0.1 port 9530
  allow { 127.0.0.1; } keys { "rndc-key"; };
};

include "/usr/local/etc/namedb/named.conf.d/*.conf";

zone "."                { type hint;    file "/usr/local/etc/namedb/named.root"; };
zone "localhost"        { type primary; file "/usr/local/etc/namedb/primary/localhost-forward.db"; };
zone "127.in-addr.arpa" { type primary; file "/usr/local/etc/namedb/primary/localhost-reverse.db"; };
zone "0.ip6.arpa"       { type primary; file "/usr/local/etc/namedb/primary/localhost-reverse.db"; };

zone "whitelist.localdomain" { type primary; file "/usr/local/etc/namedb/primary/whitelist.db"; notify no; check-names ignore; };
zone "blacklist.localdomain" { type primary; file "/usr/local/etc/namedb/primary/blacklist.db"; notify no; check-names ignore; };

logging {
  channel default_log {
    file "/var/log/named/named.log" versions 3 size 5m;
    print-time yes;
    print-severity yes;
    print-category yes;
  };

  channel default_syslog {
    print-time yes;
    print-category yes;
    print-severity yes;
    syslog daemon;
    severity info;
  };

  channel query_log {
    file "/var/log/named/query.log" versions 3 size 5m;
    print-time yes;
  };

  channel rpz_log {
    file "/var/log/named/rpz.log" versions 3 size 5m;
    print-time yes;
  };

  category default { default_syslog; };
  category general { default_syslog; };
  category config { default_syslog; };
  category dispatch { default_syslog; };
  category network { default_syslog; };
  category queries { query_log; };
  category rpz { rpz_log; };
  category lame-servers { null; };
};

