---
owner: zynf
group: zynf
data_dir: "{{ 'out/seal/data' | realpath }}"
env_dir: "{{ 'out/seal/env' | realpath }}"
quadlet_dir: "{{ 'out/quadlet' | realpath }}"
container_env: "{{ env_dir ~ '/' ~ container_name }}.env"
container_data_dir: "{{ data_dir ~ '/' ~ container_name }}"
container_image: "{{ container.image[container_name] }}"
ip: "{{ container.ip[container_name] }}"
network: macv50
dns: >
  {{
    {
      "macv10": "10.0.10.1",
      "macv50": "10.0.50.1",
      "macv70": "10.0.70.1"
    }[network] | default('')
  }}

systemd__install: |
  [Install]
  {% if unit_wantedby is defined %}
  WantedBy={{ unit_wantedby | join(' ') }}
  {% endif %}
systemd__unit: |
  [Unit]
  {% if item is defined %}
  Description={{
    container.desc[container_name ~ '-' ~ item] |
    default(
    container_name | capitalize ~ ' ' ~ item | capitalize ~ ' Container'
    )
  }}
  {% else %}
  Description={{
    container.desc[container_name] |
    default(container_name | capitalize ~ ' Container')
  }}
  {% endif %}
  {% if unit_requires is defined %}
  Requires={{ unit_requires | join(' ') }}
  {% endif %}
  {% if unit_after is defined %}
  After={{ unit_after | join(' ') }}
  {% endif %}
