server_config_yaml: "{{ _config.server.default | combine(_config.server.cilium if cilium_enabled else {}, recursive=True) | combine({'selinux': true} if ansible_selinux else {}, recursive=True) }}"
agent_config_yaml: "{{ _config.agent.default | combine(_config.agent.cilium if cilium_enabled else {}, recursive=True) | combine({'selinux': true} if ansible_selinux else {}, recursive=True) }}"

_config:
  server:
    default:
      tls-san:
        - "{{ api_endpoint }}"
      disable:
        - traefik
        - servicelb
      cluster-cidr: "{{ k3s_cluster_cidr }}"
      service-cidr: "{{ k3s_service_cidr }}"
    cilium:
      disable-kube-proxy: true
      disable-network-policy: true
      flannel-backend:
        - none
      node-taint:
        - node.cilium.io/agent-not-ready:NoExecute
  agent:
    default:
    cilium:
      node-taint:
        - node.cilium.io/agent-not-ready:NoExecute
