# ------------------------------------------------------------
# alakx.com
# ------------------------------------------------------------

server {
  listen 80;
  listen [::]:80;

  server_name alakx.com;

  access_log /var/log/angie/default-host.access.log standard;
  error_log /var/log/angie/default-host.error.log warn;

  root /usr/share/angie/html/default_www;

  location / {
    try_files $uri /index.html;
  }
}
