# ------------------------------------------------------------
# modmaster.org
# ------------------------------------------------------------

server {
  set $server         "modmaster-fpm";
  set $port           9000;

  listen 80;
  listen [::]:80;

  server_name modmaster.org;
  access_log /var/log/angie/modmaster.org.access.log proxy;
  error_log /var/log/angie/modmaster.org.error.log warn;

  root /usr/share/angie/modmaster;

  index index.php;

  include conf/http.d/include/cloudflare.conf;
  include conf/http.d/include/restrictions.conf;
  include conf/http.d/include/wordpress.conf;

  status_zone $host zone=host_zone:10;
}
