---
- name: "{{ ansible_role_name }}/step-ca: Create volume directories"
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    state: directory
    owner: "{{ _quadlet.owner }}"
    group: "{{ _quadlet.group }}"
  loop: "{{ _quadlet.mount_src }}"

- name: "{{ ansible_role_name }}/step-ca: Generate quadlets"
  containers.podman.podman_container:
    name: "{{ _quadlet.name }}"
    state: quadlet
    quadlet_dir: "{{ _quadlet.quadlet_dir }}"
    volume:
      - "{{ _quadlet.mount_src[0] }}:/home/step:Z"
    image: "{{ _quadlet.image }}"
    dns: "{{ _quadlet.dns }}"
    network: "{{ _quadlet.network }}"
    ip: "{{ _quadlet.ip }}"
    mac_address: "{{ _quadlet.mac_address }}"
    cpus: "{{ _quadlet.cpus }}"
    memory: "{{ _quadlet.memory }}"
    quadlet_options:
      - "AutoUpdate=registry"
      - |

        {{ _quadlet.__systemd_service }}
        {{ _quadlet.__systemd_unit }}
        {{ _quadlet.__systemd_install.rstrip() }}
  vars:
    systemd_service:
      Restart: always
    systemd_unit:
      After:
        - containers.target
    systemd_install:
      WantedBy:
        - containers.target
  notify:
    - SystemD daemon reload
    - restart service

- name: "{{ ansible_role_name }}/{{ _quadlet.name }}: Check if service is running"
  ansible.builtin.systemd:
    name: "{{ _quadlet.name }}.service"
  register: service_status
  listen: restart service

- name: "{{ ansible_role_name }}/{{ _quadlet.name }}: Restart if service was running"
  ansible.builtin.systemd:
    name: "{{ _quadlet.name }}.service"
    state: restarted
  when: service_status.status.ActiveState == "active"
  listen: restart service
