---
- name: "{{ task }} : Load variables"
  include_vars: "{{ task }}"

- name: "{{ task }} : Create volume directories"
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"
  loop: "{{ mount_src }}"
  vars:
    container_name: wordpress

- name: "{{ task }} : Generate quadlets [web]"
  containers.podman.podman_container:
    name: "{{ container_name }}"
    state: quadlet
    quadlet_dir: "{{ quadlet_dir }}"

    env_file: "{{ container_env }}"
    volume:
      - "{{ mount_src[0] }}:/var/www/html:Z"
    image: "{{ container_image }}"
    ip: "{{ ip }}"
    dns: "{{ dns }}"
    network: "{{ network }}"
    cpus: 4
    memory: 2G
    quadlet_options:
      - "AutoUpdate=registry"
      - "Pull=newer"
      - |

        {{ __systemd_unit }}
        {{ __systemd_install.rstrip() }}
  vars:
    container_name: wordpress-web
    unit_wantedby:
      - containers.target
    unit_requires:
      - wordpress-mysql.service
    unit_after:
      - containers.target
      - wordpress-mysql.service

- name: "{{ task }} : Generate quadlets [mysql]"
  containers.podman.podman_container:
    name: "{{ container_name }}"
    state: quadlet
    quadlet_dir: "{{ quadlet_dir }}"

    env_file: "{{ container_env }}"
    volume:
      - "{{ mount_src[1] }}:/var/lib/mysql:Z"
    image: "{{ container_image }}"
    ip: "{{ ip }}"
    dns: "{{ dns }}"
    network: "{{ network }}"
    cpus: 2
    memory: 512M
    quadlet_options:
      - "AutoUpdate=registry"
      - "Pull=newer"
      - |

        {{ __systemd_unit }}
        {{ __systemd_install.rstrip() }}
  vars:
    container_name: wordpress-mysql
    unit_after:
      - containers.target
