pki_common_name:
  root: Alakx Root CA
  infra: Alakx Infrastructure CA
  vpn: Alakx VPN CA
  acme: Alakx ACME CA

pki_organization_name: Alakx Homelab
pki_locality_name: Sumqayit
pki_country_name: AZ
pki_crl_url: http://ca.home.alak
pki_dir: /home/syno/pki

stepca:
  name: Alakx ACME
  dns:
    - ca.home.alak
    - 10.0.50.100
  provisioner: zynthasius@home.alak
