---
- name: Prepare nodes for cluster deployment
  hosts: k3s_cluster
  become: true
  roles:
    - k3s_prep
  tags:
    - k3s_prep

- name: Deploy a k3s cluster
  ansible.builtin.import_playbook: k3s.orchestration.site

- name: Install addons to the cluster
  hosts: localhost
  connection: local
  tasks:
  roles:
    - k8s_wait_ready
    - k3s_addons
  tags:
    - k3s_addons
