---
- name: Deploy a k3s cluster
  ansible.builtin.import_playbook: k3s.orchestration.site

# - hosts: k3s_cluster

- name: Install addons to the cluster
  hosts: localhost
  connection: local
  tasks:
  roles:
    - k8s_wait_ready
    - k8s_addons
