---
- name: Reload bind
  ansible.builtin.service:
    name: named
    state: reloaded

- name: Wait bind
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 53
    state: started
    delay: 2
    timeout: 15

- name: Start and enable service name
  ansible.builtin.service:
    name: named
    state: started
