---
- name: "Configure PKI hosts"
  hosts: pki_hosts
  roles:
    - role: pki
      tags:
        - pki

- name: "Configure KVM hosts"
  hosts: kvm_hosts
  become: true
  roles:
    - role: forge
      tags:
        - forge
    - role: telemetry
      tags:
        - telemetry
    - role: reverse-proxy
      tags:
        - reverse-proxy
