---
- name: "Configure Reverse Proxy on KVM hosts"
  hosts: kvm_hosts
  gather_facts: false
  become: true
  roles:
    - reverse-proxy
  tags:
    - reverse-proxy

- name: "Configure Telemetry on KVM hosts"
  hosts: kvm_hosts
  gather_facts: false
  become: true
  roles:
    - telemetry
  tags:
    - telemetry

- name: "Configure PKI on PKI hosts"
  hosts: pki_hosts
  gather_facts: false
  roles:
    - pki
  tags:
    - pki
