- name: "Reverse-proxy/angie: Create volume directories"
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    state: directory
    owner: 100  # Angie User
    group: 101  # Angie Group
    mode: "0755"
  loop: "{{ _quadlet.mount_src[:-2] }}"

- name: "Reverse-proxy/angie: Generate quadlets"
  containers.podman.podman_container:
    name: "{{ _quadlet.name }}"
    state: quadlet
    quadlet_dir: "{{ _quadlet.quadlet_dir }}"
    etc_hosts:
      host.containers.internal: host-gateway
    volume: "{{ angie.base.volumes + angie[space].volumes }}"
    image: "{{ _quadlet.image }}"
    network: "{{ angie.base.networks + angie[space].networks }}"
    cpus: "{{ _quadlet.cpus }}"
    memory: "{{ _quadlet.memory }}"
    quadlet_options: "{{ _quadlet.options }}"
  vars:
    angie:
      base:
        networks:
          - "{{ _quadlet.networks[0] }}:ip={{ _quadlet.ip }},mac={{ _quadlet.mac_address }}"
        volumes:
          - "{{ _quadlet.mount_src[0] }}:/etc/angie/angie.conf:Z"
          - "{{ _quadlet.mount_src[1] }}:/etc/angie/conf:Z"
          - "{{ _quadlet.mount_src[2] }}:/usr/share/angie/html:Z"
          - "{{ _quadlet.mount_src[3] }}:/var/lib/angie/acme:Z"
          - "{{ _quadlet.mount_src[4] }}:/var/log/angie:Z"
      internal:
        networks:
          - "{{ _quadlet.networks[1] }}"
        volumes:
          - "{{ _quadlet.mount_src[5] }}:/usr/share/angie/modmaster:z"
      public:
        networks: []
        volumes:
          - "{{ _quadlet.mount_src[6] }}:/usr/share/angie/cdn:z"
          - "{{ _quadlet.mount_src[7] }}:/usr/share/angie/hdd:ro"
          - "{{ _quadlet.mount_src[8] }}:/usr/share/angie/fastdl:ro"
    systemd_service:
      Restart: always
    systemd_unit:
      After:
        - containers.target
        - modmaster-fpm.service
      Wants:
        - modmaster-fpm.service
    systemd_install:
      WantedBy:
        - containers.target
  register: quadlet_gen
  notify: "SystemD daemon reload"

- name: "Reverse-proxy/angie: Copy etc"
  ansible.builtin.copy:
    src: "{{ space }}/etc/"
    dest: "{{ _quadlet.mount_src[0] | dirname }}"
    mode: "0644"
    directory_mode: "0755"
  register: copy_etc

- name: "Reverse-proxy/angie: Copy angie data"
  ansible.builtin.copy:
    src: "{{ space }}/data/"
    dest: "{{ _quadlet.data }}"
    mode: "0644"
    directory_mode: "0755"
  register: copy_data

- name: "Reverse-proxy/angie: Render default server config"
  ansible.builtin.template:
    src: "{{ space }}/default_server.conf.j2"
    dest: "{{ _quadlet.mount_src[1] }}http.d/default_server.conf"
    mode: "0644"
  register: render_default

- name: "Reverse-proxy/angie: Render proxy host configs"
  ansible.builtin.template:
    src: "{{ space }}/proxy_host.conf.j2"
    dest: "\
      {{ _quadlet.mount_src[1] }}http.d/\
      {% if proxy_host.hostname is string %}\
      {{ proxy_host.hostname }}\
      {% elif proxy_host.hostname is iterable %}\
      {{ proxy_host.hostname[0] }}\
      {% endif %}\
      .conf"
    mode: "0644"
  loop: "{{ services[ansible_role_name][space].proxy_hosts }}"
  loop_control:
    loop_var: proxy_host
  register: render_proxy

- name: "Reverse-proxy/angie: Render angie config"
  ansible.builtin.template:
    src: "{{ space }}/angie.conf.j2"
    dest: "{{ _quadlet.mount_src[0] | dirname }}/angie.conf"
    mode: "0644"
  register: render_angie

- name: "Run notified handlers now"
  ansible.builtin.meta: flush_handlers

- name: "Reverse-proxy/angie: Check if service is running"
  ansible.builtin.systemd:
    name: "{{ _quadlet.name }}.service"
  register: service_status
  when: >
    [
      volume_dirs,
      quadlet_gen,
      copy_etc,
      copy_data,
      render_default,
      render_proxy,
      render_angie
    ] | selectattr('changed', 'defined') | selectattr('changed') | list | length > 0

- name: "Reverse-proxy/angie: Restart if service was running"
  ansible.builtin.service:
    name: "{{ _quadlet.name }}.service"
    state: restarted
  when: >
    (
      [
        volume_dirs,
        quadlet_gen,
        copy_etc,
        copy_data,
        render_default,
        render_proxy,
        render_angie
      ] | selectattr('changed', 'defined') | selectattr('changed') | list | length > 0
    ) and service_status.status is defined and service_status.status.ActiveState == "active"

# - name: "Reverse-proxy/angie: Reload if service was running"
#   containers.podman.podman_container_exec:
#     name: "{{ _quadlet.name }}"
#     command: angie -s reload
#   when: >
#     (
#       [
#         volume_dirs,
#         quadlet_gen,
#         copy_etc,
#         copy_data,
#         render_default,
#         render_proxy,
#         render_angie
#       ] | selectattr('changed', 'defined') | selectattr('changed') | list | length > 0
#     ) and service_status.status is defined and service_status.status.ActiveState == "active"
