- name: "Reverse-proxy/angie: Create volume directories"
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    state: directory
    owner: "{{ _quadlet.owner }}"
    group: "{{ _quadlet.group }}"
    mode: "0755"
  loop: "{{ _quadlet.mount_src[:-1] }}"
  register: volume_dirs

- name: "Reverse-proxy/angie: Generate quadlets"
  containers.podman.podman_container:
    name: "{{ _quadlet.name }}"
    state: quadlet
    quadlet_dir: "{{ _quadlet.quadlet_dir }}"
    volume:
      - "{{ _quadlet.mount_src[0] }}:/etc/angie/angie.conf:Z"
      - "{{ _quadlet.mount_src[1] }}:/etc/angie/conf:Z"
      - "{{ _quadlet.mount_src[2] }}:/usr/share/angie/html:Z"
      - "{{ _quadlet.mount_src[3] }}:/usr/share/angie/cdn:Z"
      - "{{ _quadlet.mount_src[4] }}:/var/log/angie:Z"
      - "{{ _quadlet.mount_src[5] }}:/hdd"
    image: "{{ _quadlet.image }}"
    dns: "{{ _quadlet.dns }}"
    network: "{{ _quadlet.network }}"
    ip: "{{ _quadlet.ip }}"
    mac_address: "{{ _quadlet.mac_address }}"
    cpus: "{{ _quadlet.cpus }}"
    memory: "{{ _quadlet.memory }}"
    quadlet_options:
      - "AutoUpdate=registry"
      - |
        {{ _quadlet.__systemd_service }}
        {{ _quadlet.__systemd_unit }}
        {{ _quadlet.__systemd_install.rstrip() }}
  vars:
    systemd_service:
      Restart: always
    systemd_unit:
      After:
        - containers.target
    systemd_install:
      WantedBy:
        - containers.target
  register: quadlet_gen
  notify: "SystemD daemon reload"

- name: "Reverse-proxy/angie: Copy etc"
  ansible.builtin.copy:
    src: etc/
    dest: "{{ _quadlet.mount_src[0] | dirname }}"
    mode: "0644"
    directory_mode: "0755"
  register: copy_etc

- name: "Reverse-proxy/angie: Copy angie data"
  ansible.builtin.copy:
    src: data/
    dest: "{{ _quadlet.data }}"
    mode: "0644"
    directory_mode: "0755"
  register: copy_data

- name: "Reverse-proxy/angie: Render default server config"
  ansible.builtin.template:
    src: default_server.conf.j2
    dest: "{{ _quadlet.mount_src[1] }}http.d/default_server.conf"
    mode: "0644"
  register: render_default

- name: "Reverse-proxy/angie: Render proxy host configs"
  ansible.builtin.template:
    src: proxy_host.conf.j2
    dest: "\
      {{ _quadlet.mount_src[1] }}http.d/\
      {% if proxy_host.hostname is string %}\
      {{ proxy_host.hostname }}\
      {% elif proxy_host.hostname is iterable %}\
      {{ proxy_host.hostname[0] }}\
      {% endif %}\
      .conf"
    mode: "0644"
  loop: "{{ services[ansible_role_name].proxy_hosts }}"
  loop_control:
    loop_var: proxy_host
  register: render_proxy

- name: "Reverse-proxy/angie: Render angie config"
  ansible.builtin.template:
    src: angie.conf.j2
    dest: "{{ _quadlet.mount_src[0] | dirname }}/angie.conf"
    mode: "0644"
  register: render_angie

- name: "Run notified handlers now"
  ansible.builtin.meta: flush_handlers

- name: "Reverse-proxy/angie: Check if service is running"
  ansible.builtin.systemd:
    name: "{{ _quadlet.name }}.service"
  register: service_status
  when: >
    [
      volume_dirs,
      quadlet_gen,
      copy_etc,
      copy_data,
      render_default,
      render_proxy,
      render_angie
    ] | selectattr('changed', 'defined') | selectattr('changed') | list | length > 0

- name: "Reverse-proxy/angie: Restart if service was running"
  ansible.builtin.service:
    name: "{{ _quadlet.name }}.service"
    state: restarted
  when: >
    (
      [
        volume_dirs,
        quadlet_gen,
        copy_etc,
        copy_data,
        render_default,
        render_proxy,
        render_angie
      ] | selectattr('changed', 'defined') | selectattr('changed') | list | length > 0
    ) and service_status.status is defined and service_status.status.ActiveState == "active"

# - name: "Reverse-proxy/angie: Reload if service was running"
#   containers.podman.podman_container_exec:
#     name: "{{ _quadlet.name }}"
#     command: angie -s reload
#   when: >
#     (
#       [
#         volume_dirs,
#         quadlet_gen,
#         copy_etc,
#         copy_data,
#         render_default,
#         render_proxy,
#         render_angie
#       ] | selectattr('changed', 'defined') | selectattr('changed') | list | length > 0
#     ) and service_status.status is defined and service_status.status.ActiveState == "active"
