---
- name: "Webapps/hpage: Create container directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ _quadlet.owner }}"
    group: "{{ _quadlet.group }}"
    mode: "0755"
  loop:
    - "{{ quadlet.env_dir }}"
    - "{{ quadlet.data_dir }}"

- name: "Webapps/hpage: Include tasks"
  ansible.builtin.include_tasks:
    file: hpage.yml
    apply:
      tags: [webapps_hpage]
  vars:
    quadlet_mount_src:
      - "{{ _quadlet.data_dir ~ '/hpage-api/shared/' }}"
      - /var/log/beusproxy/
  tags: [webapps_hpage]

- name: "Webapps/modmaster: Include tasks"
  ansible.builtin.include_tasks:
    file: modmaster.yml
    apply:
      tags: [webapps_modmaster]
  vars:
    quadlet_mount_src:
      - "{{ _quadlet.data_dir ~ '/modmaster-fpm/html/' }}"
      - "{{ _quadlet.data ~ '/data/' }}"
      - "{{ _quadlet.data ~ '/z-innodb-mariadb.ini' }}"
  tags: [webapps_modmaster]

- name: "Webapps: Generate environment files"
  ansible.builtin.template:
    src: env.j2
    dest: "{{ _quadlet.env_dir ~ '/' ~ item.key ~ '.env' }}"
    owner: "{{ _quadlet.owner }}"
    group: "{{ _quadlet.group }}"
    mode: "0600"
  loop: "{{ services[ansible_role_name].env | dict2items }}"
