---
- name: "{{ task }} : Create volume directories"
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    state: directory
    owner: "{{ quadlet.owner }}"
    group: "{{ quadlet.group }}"
  loop: "{{ quadlet._.mount_src.values() | list | flatten }}"

- name: "{{ task }} : Generate quadlets [server/worker]"
  containers.podman.podman_container:
    name: "{{ quadlet._.container_name ~ '-' ~ item }}"
    state: quadlet
    quadlet_dir: "{{ quadlet.quadlet_dir }}"

    env_file: "{{ quadlet._.container_env }}"
    volume:
      - "{{ quadlet._.mount_src.main[0] }}:/media:z"
      - "{{ quadlet._.mount_src.main[1] }}:/templates:z"
      - "{{ quadlet._.mount_src.main[2] }}:/certs:z"
    command: "{{ item }}"
    image: ghcr.io/goauthentik/server:2025.8.1
    ip: "{{ quadlet._.ip }}"
    dns: "{{ quadlet._.dns }}"
    network: "{{ quadlet._.network }}"
    mac_address: "{{ quadlet._.ip | macgen() }}"

    cpus: 2
    memory: 512M
    quadlet_options:
      - "AutoUpdate=registry"
      - "Pull=newer"
      - |

        {{ quadlet.__systemd_unit }}
        {{ quadlet.__systemd_install.rstrip() }}
  loop:
    - server
    - worker
  vars:
    quadlet_container_name: authentik
    quadlet_ip: "{{ quadlet.container.ip[quadlet._.container_name ~ '-' ~ item] }}"
    unit_wantedby:
      - containers.target
    unit_requires:
      - authentik-sql.service
      - authentik-redis.service
    unit_after:
      - containers.target
      - authentik-sql.service
      - authentik-redis.service

- name: "{{ task }} : Generate quadlet [pgsql]"
  containers.podman.podman_container:
    name: "{{ quadlet._.container_name }}"
    state: quadlet
    quadlet_dir: "{{ quadlet.quadlet_dir }}"

    env_file: "{{ quadlet._.container_env }}"
    volume:
      - "{{ quadlet._.mount_src.pgsql[0] }}:/var/lib/postgresql/data:Z"
    image: docker.io/library/postgres:16-alpine
    ip: "{{ quadlet._.ip }}"
    dns: "{{ quadlet._.dns }}"
    network: "{{ quadlet._.network }}"
    mac_address: "{{ quadlet._.ip | macgen() }}"

    cpus: 1
    memory: 512M
    quadlet_options:
      - "AutoUpdate=registry"
      - "Pull=newer"
      - |

        {{ quadlet.__systemd_unit }}
        {{ quadlet.__systemd_install.rstrip() }}
  vars:
    quadlet_container_name: authentik-pgsql
    unit_wantedby:
      - containers.target
    unit_after:
      - containers.target

- name: "{{ task }} : Generate quadlet [redis]"
  containers.podman.podman_container:
    name: "{{ quadlet._.container_name }}"
    state: quadlet
    quadlet_dir: "{{ quadlet.quadlet_dir }}"

    volume:
      - "{{ quadlet._.mount_src.redis[0] }}:/data:Z"
    command: --save 60 1 --loglevel warning
    image: docker.io/library/postgres:16-alpine
    ip: "{{ quadlet._.ip }}"
    dns: "{{ quadlet._.dns }}"
    network: "{{ quadlet._.network }}"
    mac_address: "{{ quadlet._.ip | macgen() }}"

    cpus: 1
    memory: 512M
    quadlet_options:
      - "AutoUpdate=registry"
      - "Pull=newer"
      - |

        {{ quadlet.__systemd_unit }}
        {{ quadlet.__systemd_install.rstrip() }}
  vars:
    quadlet_container_name: authentik-redis
    unit_wantedby:
      - containers.target
    unit_after:
      - containers.target
