---
- become: true
  block:
    - name: Create container directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ owner }}"
        group: "{{ group }}"
      loop:
        - "{{ env_dir }}"
        - "{{ data_dir }}"


    - ansible.builtin.include_tasks: "{{ task }}"
      loop:
        - authentik.yml
      loop_control:
        loop_var: task

    - name: Generate environment files
      ansible.builtin.template:
        src: env.j2
        dest: "{{ env_dir ~ '/' ~ item.key ~ '.env' }}"
        owner: "{{ owner }}"
        group: "{{ group }}"
        mode: "0600"
      loop: "{{ container.env | dict2items }}"
