---
- name: "{{ task }} : Load variables"
  include_vars: "{{ task }}"

- name: "{{ task }} : Create volume directories"
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"
  loop: "{{ mount_src }}"

- name: "{{ task }} : Generate quadlet"
  containers.podman.podman_container:
    name: "{{ container_name }}"
    state: quadlet
    quadlet_dir: "{{ quadlet_dir }}"

    env_file: "{{ container_env }}"
    volume:
      - "{{ mount_src[0] }}:/data:Z"
    image: "{{ container_image }}"
    ip: "{{ ip }}"
    dns: "{{ dns }}"
    network: "{{ network }}"
    mac_address: "{{ ip | macgen() }}"

    cpus: 2
    memory: 512M
    quadlet_options:
      - "AutoUpdate=registry"
      - "Pull=newer"
      - |

        {{ systemd__unit }}
        {{ systemd__install.rstrip() }}
  vars:
    unit_wantedby:
      - containers.target
    unit_after:
      - containers.target

