# ------------------------------------------------------------
# cdn.alakx.com
# ------------------------------------------------------------

map $scheme $hsts_header {
  https "max-age=63072000; preload";
}

server {
  listen 80;
  listen [::]:80;

  root /usr/share/angie/cdn;

  server_name cdn.alakx.com root.alakx.com;
  access_log /var/log/angie/cdn.home.alak.access.log proxy;
  error_log /var/log/angie/cdn.home.alak.error.log warn;

  location / {
    # autoindex on;
  }

  location /hdd/ {
    # autoindex on;
    alias /hdd/;
  }
}

